title: Aditya Dhar
logo: /assets/img/IMG_2971.jpg
description: I'm a first-year PhD student in finance at Chicago. I graduated from Harvard in 2022.
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
